# Generated by Django 4.1.7 on 2023-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0002_post_user_engagement"),
    ]

    operations = [
        migrations.AddField(
            model_name="userengagement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
