# Generated by Django 4.1.7 on 2023-04-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0005_userposttagweightage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userposttagweightage",
            name="post",
        ),
        migrations.AddField(
            model_name="userposttagweightage",
            name="tag",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
